### ISSUE TITLE
Same put-like expression for many fields

### ISSUE THREAD

**Issue by Komosa** [johnkerl/miller#101]
It would be nice to have possibility to:
- apply simple math expression to each field, eg add 10 to each field matching `f*`;
- have possibility to use not only constants but also values form other fields, eg divide all fields matching `f*` by `f_sum`;
- have posibility to express same as above, but without temporary variable, eg divide all fields matching `f*` by sum of all fields matching `f2*`.

By now, I could only compute sum with `merge-fields`, and `then` use `put '$f0d = $f0 / $f_sum; $f1d = ...'`, but it is tedious.

**Comment by johnkerl** [comment]
I'll think about this ...........

I've thought about this kind of thing a little before but didn't want to put too much time into it since I myself have no use-case for it and as far as I could tell no one else did either.

But if you have a use for it, it's worth thinking about.

The general idea of looping over fields is absent in Miller. This could open up many more possibilities.

One is to implement your suggestion solely in terms of regex handling -- where the implicit for-loop is handled in the implementation C code but at the Miller-user level you just supply a regex. Example: `mlr rename`. This would be quicker to implement and would be less flexible.

A second possibility is I add an explicit `for` to the `mlr put` DSL. This would be a bigger feature to implement but would obviously be a powerful addition which would lend itself to solving other problems in the future.

**Comment by Komosa** [comment]
Finally I just reworked my data generation to have only three, named fields instead of 10.
And it was good move in this particular case.

For will be more flexible (be prepared for nesting feature request :P), but one of the most important reasons I use miller is simple syntax.

**Comment by johnkerl** [comment]
Yes, that's just it. `mlr stats1 -a sum -f x` is nicer than having to track summation variables as in `awk`. And the more language features Miller's put-DSL has (for-loops, if-statements, nested control structures, etc.) then the _less_ powerful it begins to seem: because of the other programming-language features it _doesn't_ have.

When I was originally prototyping this a year ago, the decision was whether to hand-code in a low-level language like C or Rust, with my own hand-rolled DSL, or whether to use a higher-level language (like Python or Lua or Nim) and let the `put` statements be handled by the implementation language's own `eval`. Multiple performance experiments showed me I could get better throughput using the former, and using C in particular -- by a wide margin. So Miller is C under the hood with a hand-rolled DSL.

Just as you point out, I do want to keep focusing on what Miller is good at -- concise notation, low latency, and high throughput -- and not add too much in terms of high-level-language features to the DSL.

That said, some sort of looping over field names is a basic thing to want. So when I said "I'll think about this" above, that's what I meant: making a concise -- and hopefully reusable -- way to loop over field names while keeping the notation concise and not opening a can of language worms.

Anyway, that's some more detail on the design decision here.

**Comment by johnkerl** [comment]
... this is doable with some simple `for`-loop syntax -- development of which is underway. Complexity is no more than `awk` so I don't fear language-bloat.

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/releases/tag/v4.1.0
