### ISSUE TITLE
Error: mlr: verb "latin1-to-utf8" not found.

### ISSUE THREAD

**Issue by paperbeatsscissors** [johnkerl/miller#1024]
I'm on a Mac running v12.3.1 and using the latest version of Miller (v6.2.0) and using either the "latin1-to-utf8" or the "utf8-to-latin1" verb results in the respective version of the error in the title. The functions are also throwing similar errors - any idea what might be causing this? Thanks!

**Comment by johnkerl** [comment]
@paperbeatsscissors these are new since the latest release [6.2.0](https://github.com/johnkerl/miller/releases/tag/v6.2.0) -- unfortunately the [docs](https://miller.readthedocs.io/en/latest/) refer to the latest code (HEAD) in this repo.

You can find 6.2.0 docs [here](https://miller.readthedocs.io/en/latest/release-docs/index.html) and/or you can get the latest HEAD-build Mac executable [here](https://miller.readthedocs.io/en/latest/installing-miller/).

**Comment by johnkerl** [comment]
Hi @paperbeatsscissors -- closing this issue out -- please let me know if we need to re-open -- thanks!! :)

**Comment by paperbeatsscissors** [comment]
@johnkerl My apologies! Yes, that clears everything up for me - thanks for the help, and thanks for such great tool!
