### ISSUE TITLE
Miller 6: about TSV and carriage return inside cells

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#1035]
Hi,
if I run `mlr --tsv cat tmp.tsv` on [this tsv](https://gist.githubusercontent.com/aborruso/f7f96ad4bc747cabb8999eafc79d1902/raw/3382d244ce28688437270860c9717b936d860fa7/tmp.tsv)

I have

```
mlr :  mlr: TSV header/data length mismatch 2 != 1 at filename tmp.tsv line  2.
```

If I use mlr 5 I have no error and it interprets properly the file. Shouldn't version 6 handle it well too?

In 6 I must set it as csv, running `mlr --csv --fs "\t" cat tmp.tsv`.

**Comment by johnkerl** [comment]
@aborruso this is a bit unfortunate but I'm not sure what to change here.

What's going on:

* Ever since Miller 2, Miller has handled [RFC-4180 CSV](https://miller.readthedocs.io/en/latest/file-formats/#csvtsvasvusvetc). That includes specific rules for how things like embedded newlines should be handled. Also note that CSV _has_ a well-defined spec.
* Up to and including Miller 5, I treated TSV as "CSV with tab separators". This was naïve on my part and it more or less worked, most of the time.
* As of PR #923 (see issues #922 and $438) we now have what you referred to as _It works, and it's great, because now it's a real TSV and TSV is a very important format in data science_.
* TSV doesn't have quite as well-defined a spec but, based on what I could find out there, as noted at https://miller.readthedocs.io/en/latest/file-formats/#csvtsvasvusvetc embedded newlines are `\n` and tabs are `\t`.
* What you have in this issue is a TSV file with embedded newlines handled the "CSV with tab separators" way.

So to process this file, use CSV format and specify tab separators:

```
$ mlr --csv --fs tab cat tmp.csv
a	b
"lorem
Ipsum"	1
a	2
```

**Comment by aborruso** [comment]
Thank you it has sense
