### ISSUE TITLE
CSV option to not quote fields starting with a leading space?

### ISSUE THREAD

**Issue by jglogan** [johnkerl/miller#1100]
First off, thank you for this tool.  It's wonderful.

I'm working with CSV data via multiple libraries/tools and have been looking into how to configure each so that they produce minimally sized output that introduce diffs unrelated to the actual data.

I've really good results so far with OpenCSV for Java, pandas for Python, and csv-stringify for JS, and Miller is most of the way there, except that https://github.com/johnkerl/miller/blob/main/internal/pkg/output/record_writer_csv_colorizer.go#L185 quotes strings that start with a space.

I suspect that this is to protect against some readers dropping leading spaces if not quoted, but it appears most writers don't have this behavior.  Would you be receptive to a PR that adds an option that specifically disables quoting for this case?  If so, any preferences for naming the option?

**Comment by johnkerl** [comment]
> quotes strings that start with a space

wow that an unintended side-effect :| 

> Would you be receptive to a PR

yes, but ... this is unintended behavior so let me first check it out please ... this might be characterized as a bug in which case no option needed ... 👀

**Comment by johnkerl** [comment]
yeah i don't like this :( 

```
$ cat x
a,b,c
1, 2,3

$ mlr --csv cat x
a,b,c
1," 2",3
```

**Comment by johnkerl** [comment]
ok @jglogan it's this:
https://github.com/johnkerl/miller/blob/36d0ed760884af4ea5009911705db0142b83b72d/internal/pkg/output/record_writer_csv_colorizer.go#L208-L209
which I copied en masse as noted at the top of the file for the reasons noted at the top of the file

they have this
https://github.com/johnkerl/miller/blob/36d0ed760884af4ea5009911705db0142b83b72d/internal/pkg/output/record_writer_csv_colorizer.go#L175
which I don't see anywhere [RFC4180](https://www.rfc-editor.org/rfc/rfc4180)

so i'm inclined to call this a bug due to my having incorporated a non-compliant 'feature' in `record_writer_csv_colorizer.go`

**Comment by jglogan** [comment]
Thanks for looking!  I was going to plumb something out with an option at that point, based on the notion that there was some reason for having it that way.  Looking forward to testing the update!

**Comment by jglogan** [comment]
Really appreciate the quick turnaround!  Looks good to me.

On my 200MB test file:

```
% wc -l aggregate-java.csv 
  604884 aggregate-java.csv
% /usr/local/bin/mlr --csv --ofs ',' --ors '\n' cat aggregate-java.csv > aggregate-mlr.csv
% cmp aggregate-java.csv aggregate-mlr.csv 
%
```
