### ISSUE TITLE
Question - different count between  "wc -l" and "mlr count"

### ISSUE THREAD

**Issue by bennyk8y** [johnkerl/miller#1158]
Hi, i have 2 files, both have same format.
```
mlr count us_leads_woocommerce_2.csv
count=423732

cat us_leads_woocommerce_2.csv | wc -
423732
```

As you can see above, the numbers aligned.
But for a different file, same format:
```
mlr count us_leads_shopify.csv
count=305141

cat us_leads_shopify.csv | wc -l
971200
```

As you can see, `mlr` returned 305,141 and `wc -l` returned 971,200 (**which is the correct result**)
What can cause this discrepancy?

**Comment by aborruso** [comment]
@bennyk8y could you share some rows of the second file?

Moreover try to set the input format: `mlr --icsv count us_leads_shopify.csv`

What's the field separator?

**Comment by johnkerl** [comment]
+1 on seeing the data files -- in particular re presence of any newlines embedded within double quotes ...

**Comment by trantor** [comment]
@bennyk8y you seem to conflate two different concepts: number of **lines** and number of **records**. `mlr` counts records, not lines.
You could have multiline text within fields of a record, so the assumption 1 line == 1 record is faulty to begin with.
That's why it's always better to use format-aware tools such as `mlr` to deal with CSV files rather than line-based *nix tools.
Although, as @johnkerl and @aborruso, only looking at the actual data will tell the real story or reveal some kind of bug.

**Comment by johnkerl** [comment]
This appears to be resolved -- please let me know if I missed anything and we can re-open. Thank you!
