### ISSUE TITLE
Add verbs to lowercase/uppercase keys

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#1215]
> Nice!  If there were also a verb to change the case of keys (e.g. lowercase, uppercase), fields could be normalized across different files without having to use the nuclear `$ = {}` option in a `put` expression 👍

_Originally posted by @archetyped in https://github.com/johnkerl/miller/issues/1167#issuecomment-1453956622_

**Comment by johnkerl** [comment]
@archetyped #1217

**Comment by archetyped** [comment]
Nice!  Do you think it would be more flexible or easier to manage if all case manipulation was under a single verb (e.g. `case` or `change-case`) with transformations passed as options (e.g. `-l` for lowercase, `-u` for uppercase, etc.)?

This allows for additional transformations (title case, sentence case, etc.) to all live under a single verb, rather than expanding the verb-space.

Certain case transformations are particularly useful when working with values (e.g. title case), so an option to specify fields for the verb to act on (like `﻿﻿unsparsify`) would be great.

**Comment by johnkerl** [comment]
On  #1215:

* `mlr upcase` is `mlr case -u`
* `mlr downcase` is `mlr case -l`
* New options `-s` and `-t` for sentence-case and title-case
* New `-f` to specify field names to be operated on (default all)

Note the first two bullets are backward-incompatible _with head_ but not with any previously released Miller version.

**Comment by johnkerl** [comment]
@archetyped I believe #1215 resolves this -- if not please let me know and we can re-open -- thanks!

**Comment by archetyped** [comment]
@johnkerl looks great, thanks!
