### ISSUE TITLE
mlr stats1: accumulator "median" not found.

### ISSUE THREAD

**Issue by sjackman** [johnkerl/miller#129]
When I use `stats1 -a median` I get the error message
```
mlr stats1: accumulator "median" not found.
```
The web page indicates
```
       * p50 is a synonym for median.
```
http://johnkerl.org/miller/doc/manpage.html

I'm using Miller 4.5.0.

Is `median` expected to work?

**Comment by johnkerl** [comment]
weird.

**Comment by johnkerl** [comment]
oh. i must have meant `p50 is how one says 'median'.` that's definitely confusing though.

**Comment by johnkerl** [comment]
not sure whether to update the docs or the code. at least the former.

if i accept `median` but immediately replace that with `p50` internally then the aggregate column names will be things like `mycolumn_p50` rather than `mycolumn_median` which only shifts the weirdness. if i accept `median` and call the output column `mycolumn_median` then that's just a smidge more work but is doable.

thanks @sjackman!!

**Comment by sjackman** [comment]
Thanks, John. Miller has become an indispensable component of my data analysis pipelines.

**Comment by johnkerl** [comment]
Thanks for the compliment! :)

**Comment by johnkerl** [comment]
`mlr stats1 -a median` also going into 5.0.0 -- thanks!!

**Comment by sjackman** [comment]
Thanks, John!
