### ISSUE TITLE
Feature Request: unnest JSON arrays

### ISSUE THREAD

**Issue by yutannihilation** [johnkerl/miller#133]
`--json-skip-arrays-on-input` is fine. But, is it possible to pass arrays as a string so that then we `nest --explode` it by `", "` as FS? A possible example is bellow:

```sh
$ echo -e '[{"name": "a", "values": [1, 2]}, {"name": "b", "values": [3, 5]}]' | \
    mlr --ijson cat
name=a,values=1, 2
name=b,values=3, 5

$ echo -e '[{"name": "a", "values": [1, 2]}, {"name": "b", "values": [3, 5]}]' | \
    mlr --ijson \
    nest --explode --values --across-records --nested-fs ", " -f values \
    then stats1 -a mean -g name -f values
name=a,values_mean=1.500000
name=b,values_mean=4.000000
```

I don't know if you are familiar with R, but unnesting with R is this easy:

```r
json_obj <- jsonlite::fromJSON('[{"name": "a", "values": [1, 2]}, {"name": "b", "values": [3, 5]}]', flatten = TRUE)
tidyr::unnest(json_obj, values)
#>   name values
#> 1    a      1
#> 2    a      2
#> 3    b      3
#> 4    b      5
````

I understand this kind of JSON is not the main targets of Miller, so I'm not sure if this feature should be included in Miller or not. But, just in case this is possible, I file this as an issue :)

**Comment by johnkerl** [comment]
Thanks for the request!

There are a few conceivable ways to handle JSON arrays in Miller:

* Do not support them; fatal when they are encountered in the input data. Obviously imperfect.
* Ignore them. Obviously imperfect.
* Ingest them as strings and allow splitting them via string-split methods. OK if the contents are non-recursive; not OK if an array contains an array (or a JSON object).
* Ingest them as strings and have `json_decode` and `json_encode` functions within the Miller DSL. Plus: TSV/CSV data having JSON in one or more columns now become handleable.
* Ingest them as Miller maps with integer keys. OK for read; not OK for writeback since arrays/objects on input become conflated as all objects on output. `mlr --json cat` modifies the input data.
* Create an array datatype within the Miller DSL, including `[ ... ]` literals. This is a rather significant project. Even then, how to output JSON in Miller's I/O formats which are tabular-only.
* Require more complex JSON input to be preprocessed using `jq`. Plus: puts the strengths of each tool where it belongs. Minus: now you have to know two expression languages.

This is something worth wanting, certainly, but it pushes at the edge of Miller as tabular-data processor and `jq` as JSON-only processor.

I lean a bit toward creating a `json_encode` and `json_decode` ... still, though, Miller is a tabular-data tool and nested JSON data structures become smashed to single-level on output. If Miller is to fully handle recursive JSON-style data structures, how to represent them in non-JSON I/O formats?

At the moment I'm dealing with this question by avoiding it: I'm working on the Windows port, and next will add a long-awaited aggregate-across-all-columns feature. After that ... maybe time to answer some hard questions about what Miller should do with JSON.

**Comment by yutannihilation** [comment]
Thanks for the detailed comment. Phew, there's a lot to consider...! Apparently, it will take time for us to come up with a good interface for nested JSON.

One thing I want to note is that, currently, exploding arrays in semi-tabular JSON data with `jq` is a bit painful work as shown bellow. This is why I think it's great if Miller has some feature for unnesting JSON.

```sh
$ echo '[{"name": "a", "values": [1, 2]}, {"name": "b", "values": [3, 5]}]' | jq '
> .[]
> | .values as $v           # assign to a variable before deleting a nested field
> | del(.values)            # delete the field
> | (. + {"value": $v[]})   # add the field one by one
> '
{
  "name": "a",
  "value": 1
}
{
  "name": "a",
  "value": 2
}
...snip...
```

> After that ... maybe time to answer some hard questions about what Miller should do with JSON.

I will wait for the time! 👍

**Comment by johnkerl** [comment]
Sorry for the delayed response. I implemented this a while back & forgot to update the task. My current best solution is that JSON array indices are converted to Miller map keys as described here: http://johnkerl.org/miller-releases/miller-5.1.0/doc/file-formats.html#Arrays. This will ship with Miller 5.1.0 (very soon, hopefully this evening.)

**Comment by yutannihilation** [comment]
Thanks! I will try 5.1.0 :)

**Comment by dotlouis** [comment]
If it can help people, I wanted to duplicate a row by "unnesting" an array in a property.

input.json
```json
[
{"title": "my awesome title", "roles": ["label1","label2"] }
]
```
OR
input.csv
```csv
title,labels
"my awesome title","label1,label2"
```

👇
output.csv
```csv
title, label
"my awesome title","label1"
"my awesome title","label2"
```

I ended up doing

`mlr --ijson --ocsv --from input.json put -q 'for(label in $labels) { emit1 mapsum($*, {"label": label}) }' then cut -x -f labels`

If like me, your input is a comma-separated string instead of an array, you can split the string beforehand like so:

`mlr --icsv --ocsv --from input.csv put '$labels = splita($labels,",")' then put -q 'for(label in $labels) { emit1 mapsum($*, {"label": label}) }' then cut -x -f labels`

**Comment by johnkerl** [comment]
thanks @dotlouis !!! :D

**Comment by aborruso** [comment]
@dotlouis for this kind of task (your input is a CSV), I use simply nest verb. 

```
mlr --csv nest --evar "," -f labels  input.csv
```

```
title,labels
my awesome title,label1
my awesome title,label2
```
