### ISSUE TITLE
tee: Nothing else but $* is teeable

### ISSUE THREAD

**Issue by sjackman** [johnkerl/miller#137]
How do I tee out a single column to the file? For example, write column B to files named by column A
```
mlr put 'tee >$A, $B'
```

**Comment by sjackman** [comment]
Well that was easy.
```
mlr print 'tee >$A, $B'
```

**Comment by sjackman** [comment]
If I did want to select multiple columns, how would I go about that?

**Comment by johnkerl** [comment]
probably a two-step process, as is ... let me think about it though.

**Comment by sjackman** [comment]
A typical use case would be wanting to output all the columns except the column being demux:
```sh
mlr put 'tee >$A, $B, $C, $D'
```

**Comment by johnkerl** [comment]
nice

**Comment by johnkerl** [comment]
It's by design that `tee` only processes `$*`. But that's a bit silly: either `$*` should be omitted from the syntax, or other maps besides `$*` should be supported.

Best idea at present is I let `tee` emit arbitrary maps, and you get your demux feature with

```
mlr put 'tee > $A, mapdiff($*, {"A":"foo"})'
```
or somesuch. Maybe with a replacement for `mapdiff` which returns a copy of the first argument with the second argument (map key) removed.

**Comment by sjackman** [comment]
In Rails that function is named `except`, perhaps `map_except`?

**Comment by johnkerl** [comment]
awesome thanks

**Comment by johnkerl** [comment]
OK, I took a look at this.

First there's a new `mapexcept` function although it won't work with `tee` ... which isn't really bad news because:

Secondly ... there's no reason for `tee` anymore; just use `emit`:

```
$ mlr --from s put -q 'emit > "myfile.".$a, mapexcept($*, "a")'

$ namecat myfile.*
######################################################## myfile.eks
b=pan,i=2,x=0.7586799647899636,y=0.5221511083334797
b=wye,i=4,x=0.38139939387114097,y=0.13418874328430463
b=zee,i=7,x=0.6117840605678454,y=0.1878849191181694

######################################################## myfile.hat
b=wye,i=9,x=0.03144187646093577,y=0.7495507603507059

######################################################## myfile.pan
b=pan,i=1,x=0.3467901443380824,y=0.7268028627434533
b=wye,i=10,x=0.5026260055412137,y=0.9526183602969864

######################################################## myfile.wye
b=wye,i=3,x=0.20460330576630303,y=0.33831852551664776
b=pan,i=5,x=0.5732889198020006,y=0.8636244699032729

######################################################## myfile.zee
b=pan,i=6,x=0.5271261600918548,y=0.49322128674835697
b=wye,i=8,x=0.5985540091064224,y=0.976181385699006
```

That's the short of it. More context, if you want: it used to be there were stream records (field names marked with `$`) and there were out-of-stream variables AKA oosvars (names starting with `@`). Stream records already come out of `put` (unless `-q`) so the idea was to use `tee` to tee stream records (i.e. `$*` only) out to files. And `emit` was intended to inject oosvars into output stream, or with redirect, out to files. Then in 5.0.0 lots of things changed: there were now functions, and local variables, and map literals, and so on, and in most places `$*` and oosvars and local variables and map literals and map-valued function return values were all just maps which you could do the same thing with. In particular, you can `emit` any of those 5.

So anyway, what's to do next:

* In addition to `mapexcept` (which already exists in head) I'll make a corresponding `maponly`
* I'll make a note about `tee` that it's not interesting and to use `emit` instead. And in a future release, just get rid of it with a backward-incompatibility note.

**Comment by sjackman** [comment]
Thanks, John! I love how active the development of `miller` is and how responsive you are to (reasonable I hope) requests.

Bikeshedding: I prefer the name `mapselect` over `maponly` for similarity to R and SQL. Are you familiar with the R's `tidyverse` package? If not, check out cheat sheets at https://www.rstudio.com/resources/cheatsheets/ such as the [Data Transformation Cheat Sheet](https://github.com/rstudio/cheatsheets/raw/master/source/pdfs/data-transformation-cheatsheet.pdf)
I think the author Hadley has done a pretty fine job choosing vocabulary and naming verbs/functions.

**Comment by johnkerl** [comment]
`mapselect` it is. You're welcome re active development -- thanks for all the great ideas!!! And, thanks for the cheat-sheet links!

**Comment by johnkerl** [comment]
http://johnkerl.org/miller-releases/miller-head/doc/reference-dsl.html#mapexcept

http://johnkerl.org/miller-releases/miller-head/doc/reference-dsl.html#mapselect

In head & will go into 5.2.0
