### ISSUE TITLE
count slower than wc

### ISSUE THREAD

**Issue by tooptoop4** [johnkerl/miller#1409]
5gb file count lines is much slower than wc, and running out of mem

```
root@pod:/# time cat file.csv  | wc -l
3142322

real    0m37.939s
user    0m0.248s
sys     0m9.799s

root@pod:/# time cat file.csv  | ./clis/mlr --csv --lazy-quotes --ho count
Killed #so does not complete

real    1m16.472s
user    0m23.307s
sys     0m7.287s
```

**Comment by johnkerl** [comment]
`wc` is operating bytes: `wc -l` is effectively counting how often the `'\n` byte appears.

Miller is parsing various formats, not all line-oriented -- e.g. JSON, or CSV wherein you can have carriage returns within cells as long as they're double-quoted -- which requires more processing.

Thus it is to be expected that `mlr count` is slower than `wc`. It could not be otherwise.
