### ISSUE TITLE
Escape dollar sign in regular expressions

### ISSUE THREAD

**Issue by dohse** [johnkerl/miller#171]
I want to escape the dollar sign in regular expressions to match against a literal dollar sign. Unfortunately I am not able to figure out how to do this. Neither using one backslash

```sh
<<<$'total\n$ 10' mlr --csv --opprint put '$total = sub($total, "^\$ ", "")'
```

nor using two backslashes

```sh
<<<$'total\n$ 10' mlr --csv --opprint put '$total = sub($total, "^\\$ ", "")'
```

works. In both cases the output is:

```
total
$ 10
```

I do not find anything for the keywords `escape`, `quoting` or `backslash` in the [DSL reference](https://johnkerl.org/miller/doc/reference-dsl.html).

I am using a current build from master:

```
> mlr --version
Miller 5.3.0
```

Thanks for looking into this!

**Comment by johnkerl** [comment]
OK so this is a bit of a puzzler. Under the hood Miller is simply using POSIX `regcomp` and `regexec`. From the manpage on my laptop (MacOS) I couldn't find anything special, except a brief note about `^` and `$` being start-of-line and end-of-line anchors.

That said, I thought to approach the problem another way, which is to simply make a new function called **ssub** (for string-substitute). This doesn't support regexes at all -- it's just for string literals. The nice thing is you don't have to escape anything because no characters are special. (Except backslashes in Miller string literals, which you need to double-backslash -- but this has nothing to do with `sub`, `gsub`, or `ssub`.)

Examples:

```
$ echo 'x=a\b' |mlr put '$y=ssub($x,"\\", "<<>>")'
x=a\b,y=a<<>>b

$ echo 'x=$25' |mlr put '$y=ssub($x,"$", "")'
x=$25,y=25

$ echo 'x=$ 25' |mlr put '$y=ssub($x,"$", "")'
x=$ 25,y= 25
```

**Comment by johnkerl** [comment]
This is in head and will go out with the next release, which will be 5.4.0.

Thanks for the feature request!!!!!!
