### ISSUE TITLE
Is the in-place processing mode faster?

### ISSUE THREAD

**Issue by NikosAlexandris** [johnkerl/miller#247]
Dear Millerians,

I use `mlr` as part of a massive processing workflow. A simple example is: collecting thousands or tens of thousands of identically structured CSV files, keeping only a number of certain columns out of the initial files, **putting two new columns**, and concatenating in one CSV file, obviously with one common header line.

**Update, making question more clear**

What would be faster?

1. Filter for columns of interest and collect all files in one, then put two new columns and redirect to a new file?
2. Filter for columns of interest and collect all files in one, then put two new columns in-place?
3. Put two new columns in-place in each input file (but that would alter the raw data), then filter and redirect all in one new file?

Every second counts as the actual overall process, involves millions of CSV output files.

**Comment by johnkerl** [comment]
@NikosAlexandris of course I would recommend a small-scale experiment to be sure but I think the 3rd would be the slowest -- for two reasons: one is because of in-place which writes to a temp file, then renames at the end. The rename is relatively quick but multiplied over thousands or tens of thousands of files, it could add up. The other reason is that Miller would have to traverse all the long lines of the non-filtered-down files to add the new columns -- shrinking your data first sounds quicker as subsequent steps should be faster.

1 & 2 are almost identical except for the final temp-file-and-rename at the end which should be non-noticeable since the price would be paid only once.

I hope this helps!

**Comment by johnkerl** [comment]
Closing -- @NikosAlexandris let me know if we need to revisit -- thanks!
