### ISSUE TITLE
head verb strangely reduces number of lines printed by tee command sooner in pipeline

### ISSUE THREAD

**Issue by kub1x** [johnkerl/miller#291]
`head` verb strangely influences previous `tee` command (previous as "sooner in pipeline"). It reduces number of lines printed into the output file. The [input.csv](https://github.com/johnkerl/miller/files/3901303/input.csv.txt) is just increasing sequence from 1 to 1000 as shown and attached. 

Using Miller v5.6.2

Steps to reproduce: 

```bash
$ wc -l input.csv # input contains one field "id" as sequence 1 -> 1000
1001 input.csv
$ head input.csv 
id
1
2
3
4
5
6
7
8
9
$ mlr --csv filter "NR<=100" then tee chunked.csv then head -n 5 input.csv
id
1
2
3
4
5
$ wc -l chunked.csv 
7 chunked.csv
$ cat chunked.csv # chunked.csv for some reason contains 6 records..?
id
1
2
3
4
5
6
$ mlr --csv --fs ';' filter "NR<=100" then tee chunked.csv input.csv | head -n 5
id
1
2
3
4
$ wc -l chunked.csv # without head verb all 100 lines are printed
101 chunked.csv
$ head chunked.csv 
id
1
2
3
4
5
6
7
8
9
$ 
```

I'd expect `tee then head` to tee all lines and then head just the few.

**Comment by aborruso** [comment]
The same for me, using 5.6.1-dev

**Comment by johnkerl** [comment]
Yeah so @kub1x and @aborruso this was intentional ... say you have a multi-gigabyte file and you do `mlr head -n 10 huge-file.dat` -- it should exit once the first 10 records are read, and never even attempt to keep reading records.

This is fine (as intended) for plain `mlr head` -- also for `mlr something then something-else then head` *as long as* those `something` / `something-else` verbs don't have side-effects.

I'm thinking about the best way to handle this -- certainly, if the `tee` verb is anywhere ahead of the `head` verb in the specified then-chain, then `head` needs to not abort the stream-ingest. That would fix this problem as reported.

Another catch though is that `tee` is a function within the `put`/`filter` DSL. In fact if there is any `print`, `eprint`, `dump`, `edump`, or `tee` within any `put`/`filter` invocation which appears in the then-chain before the `head` then `head` needs to not abort the stream-ingest ... .

**Comment by kub1x** [comment]
@johnkerl  To me, more intuitive would be if all `then`s worked like actual pipeline, so no later verb would side-effect those preceding. 

For the huge file example. If I was interested in say grouped results from just few first lines, I would put `head -n 1000 then something -g somefield then head -n 5` where 1000 is large enough to contain all data that's needed. It's users responsibility to limit input data the way he needs ASAP in the pipeline. 

Also what if first command does some grouping and the next is `head`? How is it handled? 

Also I don't know how this thing is actually programmed, but to me it sounds the next verb in pipeline should have a way to say the previous "I don't need any more data", which is what the `head` would do after obtained `n` records, but the previous command should be able to react to the signal accordingly to its own needs: 
- `cut` would stop and pass the "I don't need any more data" signal further back in pipeline, 
- `tee` would just keep reading data and writing to file, would stop passing data further down the pipeline and would not pass the signal further back. 
If the signal went all the way back through pipeline, the "file reader" would stop reading the input file. 

Other option is that only first verb affect the way the input file is being read. That way, if I do `mlr cat then head -n 5 huge_input.csv` I'm just being very stupid, but it's exactly how I imagine pipeline should work and it also aligns with how bash commands work. 

The signaling would improve here but only to save user some brain cycles I guess. 

Sorry for the long reply.

**Comment by johnkerl** [comment]
It does behave like an actual pipeline -- the only exception is the early-out for `head` so that head of huge files would be quick. Let me think about this please.

**Comment by johnkerl** [comment]
@kub1x I really like your *If the signal went all the way back through pipeline, the "file reader" would stop reading the input file* -- thank you!! This is quite nice.

I'm rewriting Miller in Go at present and this will be a very, very natural application of channels in the reader/mapper/mapper/mapper/writer chain.

**Comment by johnkerl** [comment]
@kub1x sorry about the long delay!! :^/

This is fixed for [Miller 6](https://johnkerl.org/miller6/) by https://github.com/johnkerl/miller/pull/679.
