### ISSUE TITLE
Partially OT: how to escape miller command inside parallel?

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#300]
Hi,
I have prepared these two example input files:

- example.csv https://gist.github.com/a2768e81ef94802079df8acb21b3c2eb
- loop.txt https://gist.github.com/d10c542f5f9b796388ca158b513c4619

If I run

```
parallel --colsep "\t" 'mlr --csv filter -S '$comune=="{1}"' example.csv>{1}.csv' :::: ./loop.txt
```

I have always

```
mlr DSL: syntax error at "=="
mlr filter: syntax error on DSL parse of '==....'
```

I'm not able to escape properly quotes in any way. 

Thank you

**Comment by johnkerl** [comment]
The multiple levels of escaping are indeed mind-boggling. :^/

(Aside: the *real* problem here is that shells use single and double quotes for containing things, and those don't have left-right pairs like `{}` or `()` -- so one `"` closes the previous `"` unless one plays backslashing games which quickly get complicated. LISP gets a lot of flak -- the joke is that "LISP" stands for  "lots of insidious silly parentheses". That's not what LISP stands for but if scripts were more like that -- or like TCL with its `{}` -- then this would all be a lot easier. Alas, Unix-style shells are popular and they use quotes ... so here we are.)

1. Contexts like this are one of the reasons I created `mlr put -f ...` / `mlr filter -f ...` -- so you can put the `filter` statement into a file when you can.

2. Also I Iike to put the entire `mlr ...` into a shell-script file sometimes, whenever the quote-escaping starts to make my head hurt.

... that said, here `parallel` is kind of working against those sanity-savers since it is taking the `{1}` and the `::::` from the command line and if those are in a file it won't find them. (Unless there is some advanced `parallel` syntax I'm unaware of.)

So the trick here is to move *some* things off the command line (where they need that maddening quote-escaping) and into files (where they don't).

This works for me:

Input:

```
$ cat input.dat
a=pan,b=pan,i=1,x=0.3467901443380824,y=0.7268028627434533
a=eks,b=pan,i=2,x=0.7586799647899636,y=0.5221511083334797
a=wye,b=wye,i=3,x=0.20460330576630303,y=0.33831852551664776
a=eks,b=wye,i=4,x=0.38139939387114097,y=0.13418874328430463
a=wye,b=pan,i=5,x=0.5732889198020006,y=0.8636244699032729
a=zee,b=pan,i=6,x=0.5271261600918548,y=0.49322128674835697
a=eks,b=zee,i=7,x=0.6117840605678454,y=0.1878849191181694
a=zee,b=wye,i=8,x=0.5985540091064224,y=0.976181385699006
a=hat,b=wye,i=9,x=0.03144187646093577,y=0.7495507603507059
a=pan,b=wye,i=10,x=0.5026260055412137,y=0.9526183602969864
```

Make list of unique values for parallel:

```
$ mlr --onidx uniq -f a input.dat > a-values.txt

$ cat a-values.txt
pan
eks
wye
zee
hat
```

Make a script to be called for each unique value of the `a` field:

```
$ cat single-value-executor.sh
#!/bin/bash
us=$(basename $0)
if [ $# -ne 3 ]; then
    echo "Usage: $us {input file name} {field name} {field value}" 1>&2
    exit 1
fi
input_file="$1"
field_name="$2"
field_value="$3"
# The trick here with quotes is not to put one thing inside another inside another.
# Instead put things *back outside*. So:
# * '$' is inside the single quotes
# * Back outside of the single quotes we have $filename
# * Back inside the single quotes we have =="
# * Back outside, $field_value
# * Etc.
mlr filter '$'$field_name'=="'$field_value'"' $input_file > ${field_value}.dat
```

Test-drive this before handing it off to `parallel`:

```
$ ls *.dat
input.dat

$ single-value-executor.sh input.dat a wye

$ ls *.dat
input.dat
wye.dat

$ cat wye.dat
a=wye,b=wye,i=3,x=0.20460330576630303,y=0.33831852551664776
a=wye,b=pan,i=5,x=0.5732889198020006,y=0.8636244699032729
```

Invoke `parallel`:

```
$ parallel single-value-executor.sh input.dat a {1} :::: a-values.txt

$ ls *.dat
eks.dat
hat.dat
input.dat
pan.dat
wye.dat
zee.dat

$ cat eks.dat
a=eks,b=pan,i=2,x=0.7586799647899636,y=0.5221511083334797
a=eks,b=wye,i=4,x=0.38139939387114097,y=0.13418874328430463
a=eks,b=zee,i=7,x=0.6117840605678454,y=0.1878849191181694

$ cat hat.dat
a=hat,b=wye,i=9,x=0.03144187646093577,y=0.7495507603507059
...
```

**Comment by johnkerl** [comment]
P.S. Please let me know how this works for you. If it does work, please do not close this issue as it will make a splendid cookbook example. :)

**Comment by aborruso** [comment]
@johnkerl as usual you are great, it works!!!

I have edited a little to adapt it to my input file (I have a csv as I/O and I need to use `-S` in filter:

```
mlr --csv filter -S '$'$field_name'=="'$field_value'"' $input_file >${field_value}.csv
```

Thank you very much

**Comment by johnkerl** [comment]
@aborruso I don't think there's anything more to add here -- please correct me if I'm wrong and we can re-open -- thank you!

See also https://miller.readthedocs.io/en/latest/scripting/
