### ISSUE TITLE
brew installation message

### ISSUE THREAD

**Issue by lsloan** [johnkerl/miller#343]
I installed miller using Homebrew for macOS.  The output was:

```
$ brew install miller
==> Downloading https://homebrew.bintray.com/bottles/miller-5.7.0.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/…
==> Pouring miller-5.7.0.mojave.bottle.tar.gz
🍺  /Local/Cellar/miller/5.7.0: 6 files, 887.7KB
```

I was disappointed that the installation didn't finish with a message like:

```
🍻 It's Miller Time! 🍻 
```

I don't know whether that would be possible, but it'd be very cool.  I know, it would probably involve a change to the Homebrew formula, but I figure the maintainers of this repo are probably the best ones to lobby for this change.

Good luck!

**Comment by johnkerl** [comment]
:)

Actually I didn't name it for a beer ... http://johnkerl.org/miller/doc/etymology.html ;)

but thanks for letting me know -- I didn't even know this was a pattern.

**Comment by lsloan** [comment]
Yeah, I read the etymology.  Very nice.  I only thought of the "Miller Time" slogan later because of Homebrew and its use of the beer mug emoji.

Maybe you'd want to lobby the Homebrew people to give Miller an installation message like:

```
🃏 Some people call me Maurice
```

FWIW, before I read the etymology, I thought Miller was named for the profession, because it runs data through a "mill" to put it in a new format.

**Comment by johnkerl** [comment]
Yeah "mill" too was something in my mind. I'm realizing I didn't write that down; I need to.

"Some people call me Maurice", wow @lsloan, I cannot even BEGIN to tell you how happy this makes me. :) :) :)

**Comment by johnkerl** [comment]
BTW http://johnkerl.org/miller-releases/miller-head/doc/etymology.html https://github.com/johnkerl/miller/commit/443e05673dedc010b12f4276c5ce0c1090baf007

**Comment by sloanlance** [comment]
I discovered this is called a "caveat" in Homebrew, so I've added one and opened a pull request.  (I'm using my personal account for this, rather than my work one.)

**Comment by sloanlance** [comment]
FWIW, after I installed Miller on my computer with the updated formula, asking for info about it gives these results:

```
$ brew info miller
miller: stable 5.7.0 (bottled), HEAD
Like sed, awk, cut, join & sort for name-indexed data such as CSV
https://github.com/johnkerl/miller
/Local/Cellar/miller/5.7.0 (6 files, 887.8KB) *
  Built from source on 2020-07-02 at 18:59:08
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/miller.rb
==> Dependencies
Build: autoconf ✔, automake ✔, libtool ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
🃏 Some people call me Maurice 🃏
==> Analytics
install: 94 (30 days), 402 (90 days), 2,198 (365 days)
install-on-request: 94 (30 days), 395 (90 days), 2,056 (365 days)
build-error: 0 (30 days)
```

**Comment by johnkerl** [comment]
I love this so much!! Thanks @sloanlance !!!!!

**Comment by sloanlance** [comment]
You may have noticed in Homebrew/homebrew-core#57327, there's some pushback.  They say Homebrew `caveats` are meant for technical notes about the way the application is installed, notably anything special about the way it was installed with Homebrew.  If we can think of something legitimate to add to the caveat, then we could probably keep this message there, too.  Otherwise, we may need to give up on that approach.

Other ideas if the caveat doesn't work out:

1. Add "Some people call me Maurice" to Miller's GitHub repo description or its official website.  That seems to be the text used for Homebrew's `description` part of the formula.  It may not be shown during installation, like `caveats` are, but it would still appear when the user requests info about the `miller` formula.
1. Add an Easter egg to `mlr` that prints the "Maurice" message.  Maybe add it as a second line that's output when the `--version` option is used.  That may not be shown when Homebrew users install or request info about the formula, either, but it would be visible to all users, even those that don't use Homebrew.

🤷

**Comment by SMillerDev** [comment]
>  If we can think of something legitimate to add to the caveat, then we could probably keep this message there, too. Otherwise, we may need to give up on that approach.

You can not, caveat blocks are really only for caveats.

**Comment by sloanlance** [comment]
To be sure we understand, the `caveats` couldn't include that message, along with other details?  E.g.:

```
==> Caveats
Important info here about the Homebrew installation of Miller.
🃏 Some people call me Maurice 🃏
```

**Comment by johnkerl** [comment]
bummer :(

does any other brew package have this niceness?

**Comment by SMillerDev** [comment]
> To be sure we understand, the caveats couldn't include that message, along with other details?

No, people expect caveats to relay caveats about the software. Putting descriptions or jokes there would make it much harder for people to grasp what a caveat is.
The best solution is letting the command print it or putting it in the manpage/other docs.

I also don't know any package manager that would allow you to use it's documentation features for jokes.

**Comment by johnkerl** [comment]
> I also don't know any package manager that would allow you to use it's documentation features for jokes.

OK we should probably let this go then. Thanks everyone for the discussion though! :)
