### ISSUE TITLE
cannot use --prepipe in Windows 10

### ISSUE THREAD

**Issue by joysan7** [johnkerl/miller#350]
Miller provides awesome facilities for working with large csv files. However, I cannot figure out how to work with compressed csv files using `--prepipe` in Windows 10 console. For example,

Check a small gzipped csv file:
```
gunzip -dcq test.csv.gz
id,name
100,alice
200,bob
300,carol
```
I tried using the following command as documented at https://johnkerl.org/miller/doc/reference.html#Compression:

`mlr --prepipe 'gunzip -dcq' --icsv --opprint cat test.csv.gz`

But the result is:
```
mlr: Couldn't popen "gunzip < 'test.csv.gz'" for read.
gunzip < 'test.csv.gz': No such file or directory
```

How to use `--prepipe` with gunzip in Windows 10 console? When resolved, I need to use `--prepipe` to join two gzipped files.

_Note: gunzip binary for windows downloaded from http://www2.cs.uidaho.edu/~jeffery/win32/gunzip.exe_

**Comment by aborruso** [comment]
Hi @san-r 


> > "Accessing Windows files from Linux is considerably slower than using the native Linux file system. Where possible, create projects within the Linux file space, typically within your home folder (`/home/<yourname>/` or `~`)."

I do not know, but probably it's true.

I have done a test for you. I have downloaded this zipped CSV (http://dati.mit.gov.it/catalog/dataset/e9b45e54-943f-4bfb-8dff-b3e3026743fa/resource/241d337d-5469-4f57-a002-fe4a23944b41/download/parcocircolantesicilia.csv.zip). The uncompressed size is 530 MB.

Using prepipe as Windows file and running

```
mlr --prepipe gunzip  --csv --implicit-csv-header cat then filter '$5=="AUDI"' parcocircolantesicilia.csv.zip >audi.csv
```

I have the output in 14.648 seconds.

Running the same as Linux file, I have the output in 11.365. Probably it's a similar time, because the prepipe process probably runs in Linux environment.

> 
> Since I have to keep my huge (largest uncompressed .csv table size ≈84 GB which has been gzipped to ≈21 GB) data files in an external hard drive, I may have to deal with slower access. But getting the work done slower is certainly better than not getting it done at all. Any tips for increasing performance (besides moving large sized data files within native Linux file system) will be appreciated.

Could you share a portion of your CSV? A 1 GB compressed one? In this way we can run some test in parallel.

> 
> Besides using `miller` at its best, may I ask what other great things you do with WSL?

There are a lot of data tools that work only on a Linux machine. Moreover using bash to create data pipelines is really powerful and simply. A great free ebook is https://www.datascienceatthecommandline.com/1e/

**Comment by san-r** [comment]
Thanks @aborruso. [https://www.datascienceatthecommandline.com/1e/index.html](https://www.datascienceatthecommandline.com/1e/index.html) is indeed a great resource.

I'm afraid it's not possible to share any part of my csv since it has been provided to me in an official capacity as a statutory auditor and I'm legally bound to keep it completely confidential. Nevertheless, I'm thankful for your inputs.

**Comment by san-r** [comment]
Just wanted to say "Hello" and check if work on this bug on Windows 10 platform is still on.

**Comment by san-r** [comment]
I think there should be a built-in support for gzipped csv files just like many data analysis packages in R, Python, KNIME etc. Even one command line tool called xsv (https://github.com/BurntSushi/xsv) has it.

**Comment by aborruso** [comment]
@johnkerl I have made a simple test running `mlr.exe --prepipe gunzip --csv cat input.zip`:

- using the go version I have

```
mlr :  fork/exec /bin/sh: The system cannot find the path specified
```

- using the C version I have

```
mlr: Couldn't popen "gunzip < 'input.zip'" for read.
gunzip < 'input.zip': No such file or directory
```

**Comment by johnkerl** [comment]
Hi @san-r @joysan7 @aborruso !

I don't know it happened but I don't recall seeing this issue until just now. :(

Good news for the Go port is you don't need `--prepipe` anymore for `.gz`, `.bz2`, and `.z` as those can be handled in-process without needing an external shell.

I'll look into in-process support for `.zip` in Go.

I'll also check into `--prepipe` on Windows with Miller 6. (The above reference to `/bin/sh` makes me think the above was run with Miller 5, and definitely prepipe support on Windows is not strong in Miller 5.)

**Comment by johnkerl** [comment]
@san-r @joysan7 @aborruso https://github.com/johnkerl/miller/pull/585 makes `--prepipe` work on Windows in the [Go port](https://github.com/johnkerl/miller/blob/main/go/README.md).

**Comment by aborruso** [comment]
@johnkerl it works, thank you!!

I have tried `mlr.exe --prepipe gunzip --csv cat input.zip`

**Comment by san-r** [comment]
Great news. I'll download the Windows 10 binaries.

**Comment by aborruso** [comment]
You have it here
https://github.com/johnkerl/miller/actions/runs/974353729

Il dom 27 giu 2021, 14:01 san-r ***@***.***> ha scritto:

**Comment by san-r** [comment]
Thanks for the download link. Just tested it out and found that --prepipe works perfectly fine; although with the in-built support for gzipped csv files I won't be needing it at all. Awesome job. Thanks again.
