### ISSUE TITLE
[enhancement] Wildcards in column names

### ISSUE THREAD

**Issue by Komosa** [johnkerl/miller#37]
It will be nice to say something like `mlr put '$*bytes = $*_in_bytes + $*_out_bytes'` 
or `mlr cut -x -f '*_in_*,*_out_*'`

For my use cases I made some bash wrappers to provide described behaviour.

Computation cost should be low, we need recalc this only when header changes.

**Comment by Komosa** [comment]
Maybe it will be easier now, since regex support is added :)

**Comment by johnkerl** [comment]
Duping tohttps://github.com/johnkerl/miller/issues/72

**Comment by johnkerl** [comment]
Regex support (https://github.com/johnkerl/miller/issues/72) is released in 2.3.0: https://github.com/johnkerl/miller/releases/tag/v2.3.0

The remaining case requested here, `mlr put '$*bytes = $*_in_bytes + $*_out_bytes'`, is unresolved as I don't know how align the various matches on `*`, e.g. if there are fields `this_in_bytes`, `that_out_bytes`, `the_other_in_bytes`, `this_out_bytes`, etc. in the data.

**Comment by Komosa** [comment]
I was thinking a bit more about this feature.
It will be nice to have possibility to provide regexp `re` by which all fields names will be truncated.
If there are two (or more) fields with identical names, their content should be aggregated (for completeness it is possible to specify what kind of aggregation should be applied (as in `stats1 -a`), `sum` will be good default).

Example:

    echo a_in_x=1,a_out_x=2,b_in_y=4,b_out_z=8 | mlr merge -r 'in_|out_'

will give us:

    a_x=3,b_y=4,b_z=8

**Comment by johnkerl** [comment]
I like this quite a bit.

There are a couple design decisions. (1) One is whether to use words like `sum` (imitating `stats1`) or operators such as `+` (imitating the DSLs in `mlr put` and `mlr filter`). (2) Another is how to handle cases when field names in the input data don't neatly pair up -- e.g. what if there are three field names matching a given RE. This second issue has two subissues: (2a) one is how to apply binary operators if DSLs are used; (2b) another is overlapping names.

(2b) is a non-issue since RE-matching is an equivalence relation: if field A matches field B and B matches C then A matches C. So given an RE and a record, there will be fields not matching the RE (easy no-op), accompanied by one matching (unary aggregation), two (binary aggregation), or more (n-ary aggregation). Supporting the arity flexibly leads me to think (1) should be answered by using words rather than DSL expressions: DSL expressions have fixed arity (unary, binary, etc. operators) whereas this `mlr merge` is semantically an aggregation over a list of values. This also makes (2a) a non-issue.

On the other hand, the primary benefit of DSLs is their extensibility and flexibility, whereas with `sum` et al, everything needs to be hand-crafted.

OK so I think a good idea would be an experiment using `mlr merge` with `-a` options `sum`, `count`, `min`, `max`. Also I think the words should appear in the output field names, e.g. in your example,

```
a_sum_x=3,b_sum_y=4,b_sum_x=8
```

**Comment by Komosa** [comment]
I like all of your ideas.
Especially putting operators in output names of unary aggregated fields.

**Comment by johnkerl** [comment]
OK, recent commits ending in https://github.com/johnkerl/miller/commit/230fafacd74d6b2f2f067fe0320326fb5aad15f9. Also http://johnkerl.org/miller/doc/reference.html#merge-fields.

Please let me know what you think.

**Comment by Komosa** [comment]
Cool! :+1: 
Especially `-c` is a great improvement :)
