### ISSUE TITLE
Move documentation to repository/Wiki

### ISSUE THREAD

**Issue by pabloab** [johnkerl/miller#375]
Considering that the documentation of a project is part of itself, please move the documentation to this repo. Right now the documentation is difficult to read (both format and content) and is not easy for the community to send PR to improve it (extend it, translate it...).

**Comment by johnkerl** [comment]
Thanks for the feedback! (This will be a non-trivial project due to the amount of autogen involved ..., but as you point out the effort may well be worth the time involved.)

What do you think would make it more easy to read?

**Comment by pabloab** [comment]
I'm glad you are open to the suggestion! I'm not a specialist in the area, but I would go to move everything to Markdown and generate the docs with [Sphinx](https://www.sphinx-doc.org/en/master/usage/quickstart.html) (another [great intro](https://www.writethedocs.org/guide/writing/beginners-guide-to-docs/)).

Some great Sphinx features are: generate several or a single HTML, PDF, epub; check spelling, check links in the documentation and generate .po files for translation.

The generated docs [could be hosted](https://daler.github.io/sphinxdoc-test/includeme.html) on Github Pages.

About the content itself, a beginners guide (maybe based on 10-minute intro or `curl cht.sh/mlr`) with a bunch of curated examples would be greatly appreciated.

**Comment by johnkerl** [comment]
What do you think of http://johnkerl.org/miller/doc/10-min.html ?

**Comment by johnkerl** [comment]
A very sketchy start on the port is at http://johnkerl.org/miller-releases/miller-head/docs/_build/html/

I haven't set up the commit hooks to readthedocs but I will soon.

https://github.com/johnkerl/miller/blob/master/docs/README.md is in progress.

**Comment by aborruso** [comment]
@johnkerl  this is really a great thing!!!

Thank you @pabloab for your proposal

**Comment by johnkerl** [comment]
OK v2 docs are here: https://miller.readthedocs.io/en/latest/

I need to double-check the readthedocs build is really running as a commit hook on the johnkerl/miller repo.

Regarding structure: I'm happy to port over the existing docs to Sphinx, page by page ... also I'm eager to hear thoughts from Miller users about how the v2 docs could be structured differently from the v1 docs, in order to be more useful.

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/blob/master/docs/README.md has a contributor's-guide section in it.

**Comment by johnkerl** [comment]
I am bulk-moving/translating the pages to Sphinx with the page structure as-is -- but only the more easily to refactor it there.

**Comment by johnkerl** [comment]
OK source-wise everything is moved from `doc/` (pre-Sphinx) to `docs/` (Sphinx). Likewise https://johnkerl.org/miller and https://johnkerl.org/miller/doc redirect to https://miller.readthedocs.io/.

Also the base README.md and the https://github.com/johnkerl/miller settings point to https://miller.readthedocs.io

I've done some doc-reorg but there's more to do. Also I'm eager for feedback on docpages which should be reduced/removed. Etc. Please keep the feedback coming! :)

**Comment by pabloab** [comment]
I'm very happy with all this beautiful news!

About the aesthetics, I wonder if there is available some premade nice theme templates. At least considering changing the too-obscure brown background of code sections (#c5b690).

About the content: I didn't read completely the 10' minute intro (I will), but probably it takes much more than 10'. I learn about miller on [this Unix SE answer](https://unix.stackexchange.com/a/587115/209677). I reach the docs trying to understand what the `--nidx` means. TBH I read the reference and man page and still don't understand it (I have some background, I'm a software engineer).

**Comment by johnkerl** [comment]
OK thanks, that's good to hear.

The pre-made templates, I didn't like the existing color schemes. (There aren't many.) Certainly I can improve the contrast though, for sure! Lightening up the brown background in particular, thanks for pointing that out! :)

The reference ... thanks for the feedback. I do somewhere want to have all the full details, even if people don't understand them at first, since it's important to win over power users and power users are going to want an authoritative answer to the questions that don't come up right away. Even then, the full-details pages should be as accessible as possible ... . At the very least I can flag the reference pages with "Don't start here -- these are for looking up authoritative answers to details, not a starter guide" ... and probably even more can be done here.

The manpage -- let me think about it. The more info I hear from other people, the better -- the manpage structure makes sense to me but it's not me that it needs to make sense to. :^/

10-minute, maybe could be split up -- into the first-10-minutes part, and some more stuff (like the log-analysis stuff, doesn't belong in the 10-minute intro ......)

**Comment by aborruso** [comment]
> I reach the docs trying to understand what the `--nidx` means. TBH I read the reference and man page and still don't understand it (I have some background, I'm a software engineer).

@pabloab  It's in some way a CSV in which the field separator is a (ore more) space, with an hidden header row, in which each field name is a progressive number starting from 1.

Then if you have a "regular" CSV as

```
date,name
2020-02-18,bob
2020-03-18,tom
```

its nidx representation will simply be

```
2020-02-18 bob
2020-03-18 tom
```

There a lot of UNIX files thar are CSV separated by spaces, without any header. 

If you want to apply in example a filter to a nidx file, you could use the hidden indexed header row. 
Running `mlr --nidx filter '$2=="bob"' input.nidx` you will have `2020-02-18 bob`. `$2` is the second field.

`--nidx` strictly mean that Miller will use nidx both as a input and as a output format.

I hope I was helpful

**Comment by johnkerl** [comment]
See also https://miller.readthedocs.io/en/latest/file-formats.html#nidx-index-numbered-toolkit-style

**Comment by johnkerl** [comment]
@tieguy fixed and THANK YOU!! :)

**Comment by johnkerl** [comment]
The move to https://miller.readthedocs.io/en/latest/ is long-since complete. I thought to perhaps leave this issue open for folks to submit more feedback on the context of the docs ... perhaps it's best to let that happen organically via new issues.
