### ISSUE TITLE
Gather values according to column, separated by comma

### ISSUE THREAD

**Issue by sergioronei** [johnkerl/miller#376]
Hello guys! I'm using the miller for the first time. 
I have a very specific situation where I need to handle data from a CSV.

Currently the CSV looks like this:

```
fruit;weight;color
apple;1;red
apple;2;blue
apple;2;red
banana;2;yellow
grape;4;purple
grape;5;red
```

What I need, is that to join all the FRUIT values that are equal, and in the same way, all the other items of the other columns that share rows with the same FRUIT.

The end result needs to be something like:

```
fruit;weight;color
apple,apple,apple;1,2,2;red,blue,red
banana;2;yellow
grape,grape;4,5;purple,red
```

I'm trying with this command:

`mlr --csv --fs ";" nest --implode --values --across-records --nested-fs "," -f fruit teste.csv`

but when I run the command, the output is the CSV, without changes:

```
fruit;weight;color
apple;1;red
apple;2;blue
apple;2;red
banana;2;yellow
grape;4;purple
grape;5;red

```

Could you help me?
Thank you a lot! 😃

**Comment by sergioronei** [comment]
PS: When I run the script, it repeats exactly the content of the CSV.

**Comment by aborruso** [comment]
Hi @sergioronei nest verb works only on one field, it would concatenate (in you example) only fruit field and not also weight and color.

And it concatenates by field when it finds rows that are equal. Than if you have

| fruit | weight | color |
| --- | --- | --- |
| apple | 1 | red |
| apple | 2 | blue |
| apple | 2 | red |
| banana | 2 | yellow |
| grape | 4 | purple |
| grape | 1 | red |

it implodes the fruit column of rows 1 and 6, because they are equal and you will have


| fruit | weight | color |
| --- | --- | --- |
| apple;grape | 1 | red |
| apple | 2 | blue |
| apple | 2 | red |
| banana | 2 | yellow |
| grape | 4 | purple |


Using Miller, probably you must write some [DSL script](http://johnkerl.org/miller/doc/reference-dsl.html)

**Comment by johnkerl** [comment]
@sergioronei this seems to work:

```
mlr --csv --fs semicolon --from teste.csv put -q '
  @records_by_fruit[$fruit][NR] = $*;
  end {
    for (fruit, records_for_fruit in @records_by_fruit) {
      fruits = {};
      weights = {};
      colors = {};
      for (nr, record in records_for_fruit) {
        fruits[nr] = record["fruit"];
        weights[nr] = record["weight"];
        colors[nr] = record["color"];
      }
      emit {
        "fruit": joinv(fruits, ","),
        "weight": joinv(weights, ","),
        "color": joinv(colors, ","),
      }
    }
  }
'
```

**Comment by sergioronei** [comment]
my God!!! It Works perfectly!!!!!!!!!!

John, you have no idea how important this is !!! I thank you immensely, and also the aborruso. 

I wish the best for you! I wish you win the lottery and be happy for the rest of your lives =D

Great hug!!!!!!

**Comment by sergioronei** [comment]
One last question... there is a way to set a output file to save the CSV?

Thank you again!!!

**Comment by sergioronei** [comment]
Reading the documentation, I learn how to.

teste.csv > output.csv

Thank you one more time! 😄

**Comment by johnkerl** [comment]
:):)

just end it with `> teste-nuove.csv`
