### ISSUE TITLE
mlr unsparsify -f

### ISSUE THREAD

**Issue by johnkerl** [johnkerl/miller#387]
Hey Shaun long time no see! :) I hope all is well with you.

Do you mean: if `mlr unsparsify foo.dat` then operate on all columns; if `mlr unsparsify -f a,b,c foo.dat` then only add new fields if they're named one of `a`, `b`, or `c` -- ?

_Originally posted by @johnkerl in https://github.com/johnkerl/miller/issues/77#issuecomment-725187567_

**Comment by johnkerl** [comment]
@sjackman re "Yes! And the primary motivation is to be able to stream mlr unsparsify for large datasets" (from #77) -- I don't see how to do this in a streaming manner. :(

The idea of `unsparsify` is if there is either

```
a=1,b=2,c=3
a=4,b=5
```

or

```
a=4,b=5
a=1,b=2,c=3
```

to fill in the missing `c=` value -- it's not known until the end of processing whether the field `c` exists in some record farther along in the input.

As I understand it `-f` would restrict the set of field names to touch -- but making this streaming (which is a different thing) would break the contract of what `unsparsify` does.

My suggestion would be to split out `-f a,b` from a `--streaming` flag. If `--streaming` is absent, do as now; if `--streaming` is present, only use *past* rows (and not future ones) to decide what to add to the current row.

Will this work for you?

**Comment by sjackman** [comment]
My motivation to specify `-f` not to restrict the fields (although that is a side effect) but to fully specify the fields to modify, so that it's known in advance, in which case it's not necessary to first read all of the data.

```console
$ printf "a=4,b=5\na=1,b=2,c=3\n" | mlr unsparsify --fill-with NA
a=4,b=5,c=NA
a=1,b=2,c=3
```

Note that with `-f a,b,c` the behaviour is identical (other than it using less memory because it's streaming), so I do not believe that the contract is broken.

```console
$ printf "a=4,b=5\na=1,b=2,c=3\n" | mlr unsparsify -f a,b,c --fill-with NA
a=4,b=5,c=NA
a=1,b=2,c=3
```

**Comment by sjackman** [comment]
`mlr unsparsify --streaming` doesn't work for my use case, because it's not guaranteed that the order of the rows will be suitable, with all the fields present in rows before rows that are missing those fields.

`mlr unsparsify --streaming -f a,b,c` doesn't make sense to me, because it seems to me that `--streaming` should be implied when `-f a,b,c` is specified, because when the columns are specified at the command line, you have all the information that you need, and a full first pass of the data to collect the column names is not needed.

**Comment by johnkerl** [comment]
Derp. Of course. Thanks @sjackman !! :D

**Comment by johnkerl** [comment]
Hey @sjackman -- this is in head -- please let me know what you think! :)

**Comment by sjackman** [comment]
Thanks again, John! I'll give it a go with the next stable release. 😁
