### ISSUE TITLE
Default value of uninitialized variables for multiplication: docs vs awk

### ISSUE THREAD

**Issue by torbiak** [johnkerl/miller#431]
The [DSL reference](https://miller.readthedocs.io/en/v5.10.0_a/reference-dsl.html) says:

> Since uninitialized out-of-stream variables default to 0 for addition/substraction and 1 for multiplication when they appear on expression right-hand sides (as in awk), ...

while the [POSIX awk spec](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/awk.html) says:

> An uninitialized value shall have both a numeric value of zero and a string value of the empty string.

There's a contradiction here. I checked the versions of gawk and mawk on my machine and they're consistent with POSIX, defaulting to zero for multiplication. I was quite surprised by the default value of 1 for multiplication in miller, as I wasn't intentionally relying on it but instead getting unexpected results by accidentally using an uninitialized local instead of an out-of-stream var.

Personally, a default of 1 for multiplication seems dangerously confusing to me since unintentionally using it can produce a result that seems reasonable if the intention was to multiply by a factor near 1, and I've never heard of context-specific default values within a type before. Was the intention of miller to be consistent with awk? Are there other tools that have "default of 1 for multiplication" behaviour?

Some possible paths:
- change the default for multiplication (a breaking change, but consistent with traditional tools)
- add a strict mode that prohibits using uninitialized variables (avoid/mitigate this issue, and useful in its own right)
- just update the docs

**Comment by johnkerl** [comment]
Thanks @torbiak!! Good catch.

Regarding the "(as in awk)" ... I can only believe I thought it was true at the time; certainly, I was mistaken.

Thinking back now, I would have said that I intended Miller to be somewhat awk-inspired (in part -- inspired by many things) -- but a tool of its own. But you're quoting back the "(as in awk)" which I myself wrote ... and which I'd since forgotten about until you reminded me.

As for what action to take --

Were I doing this from scratch, I think your arguments are certainly compelling enough to go with an uninitialized-is-zero rule. But preserving backward compatibility with previous Miller versions is, I think, more important than preserving compatibility with awk, or with "traditional tools" more broadly. I'm reluctant to make a change which will cause people's scripts to break in ways they don't even understand -- my experience is that code, once written, outlives the understanding of its authors, or the involvement of its authors. That is to say, we write something ourselves and keep using it and forget the details of what went into it, or, we leave a team or an employer and someone else is using the thing we wrote.

I will definitely update the docs.

Regarding a strict mode ... I've thought about this on and off for a while but it never reached the "activation energy" for me to implement it. I think it's a great idea.

Some more context on that:

* For larger software projects I'm a strong advocate for strong typing -- I really like Go and Java for these reasons (and C/C++); life is much better with Hack and Flow/Typescript than with JS and PHP; Python's `typing` module is a great addition and is really essential for large projects; I only use Ruby in very short-length scripting contexts. In particular, there's just zero chance I'd have written Miller itself using a non-typed implementation language. Same for any high-lines-of-code-count project.
* But the Miller DSL is different. It's low-lines-of-code, and I wanted people (including me) to be able to do things like `$z = $x + $y` with a minimum of keystroking/boilerplate. The typedecls like `num` / `str` / `var` etc I intended to be optional, and opt-in. And the pass-through functions like `asserting_num($x)` or `asserting_present($x)` are likewise opt-in. But sadly they are not low-keystroke options.
* For my own background using highly heterogeneous data in JSON and DKVP formats, I very very much wanted to deal with absent data in the most low-keystroke-possible way -- hence `$z=$x+$y` results in no assignment if either `$x` or `$y` is not present in the input record, and this is intentional.
* That said, lots of people (myself included) use CSV where record-to-record heterogeneity is less of an issue, where something being 'absent' is more likely due to a typo. And the DSL should be a help there, not a hindrance. The very flexibility that a heterogeneous-data-friendly absent-data mode provides makes the DSL more error-prone sometimes.

A strict mode would, I think, wrap all field-variable / localvar / oosvar reads in an implicit `asserting_present(..)` -- ? But with some opt-out syntax like `$?x` (or something) to indicate that a field might not be present in a given record?

**Comment by torbiak** [comment]
Thanks for the explanation (and so quickly!). I agree with all your points.

Regarding my motivation for a strict mode, the main mistake I seem to make is waffling between using oosvars and locals and then forgetting to add/remove the `@` sigil for one of the uses, I suppose since there's rarely more than a few handfuls of lines and changing the sigil doesn't immediately make me think to do a full search and replace. In some of these cases I wish the interpreter could find my mistake for me, but yeah, it's never enough code that tracing through it isn't fruitful in short order.

> Regarding the "(as in awk)" ... I can only believe I thought it was true at the time; certainly, I was mistaken.

It was plausible to me: there is a symmetry appeal in defaulting to an identity operation.

> ...hence $z=$x+$y results in no assignment if either $x or $y is not present in the input record, and this is intentional.

hmmm, am I missing something? For NR=2, `c` gets assigned despite `a` not existing:

    $ mlr --version
    Miller v5.10.0-dev
    $ echo -e 'a=1,b=1\nb=1' | mlr put '$c = $a + $b'
    a=1,b=1,c=2
    b=1,c=1

> A strict mode would, I think, wrap all field-variable / localvar / oosvar reads in an implicit asserting_present(..) -- ? But with some opt-out syntax like $?x (or something) to indicate that a field might not be present in a given record?

oh, cool. I didn't consider an opt-out syntax for a strict mode, but it could also double as concise documentation for fields expected to be missing, even if strict mode isn't in use.

**Comment by johnkerl** [comment]
> hmmm, am I missing something

yes i totally misspoke ;)

if `$x` and `$y` are _both_ undefined in the current record then there is no `$z` assigned by `$z = $x + $y`. but of course if one or the other is present, the missing one is treated as zero.

> but it could also double as concise documentation for fields expected to be missing, even if strict mode isn't in use.

ah cool, double win! :)

**Comment by johnkerl** [comment]
> In some of these cases I wish the interpreter could find my mistake for me

there might be an opportunity for some read-before-write validation check on the AST ...

**Comment by johnkerl** [comment]
@torbiak I played around just a little on this branch: https://github.com/johnkerl/miller/tree/uninit-warnings (this is Miller 6).

It works great here:

```
$ mlr -n put -v 'z=x+y'
DSL EXPRESSION:
z=x+y

AST:
* statement block
    * assignment "="
        * local variable "z"
        * operator "+"
            * local variable "x"
            * local variable "y"

Variable name x might not have been assigned yet.
Variable name y might not have been assigned yet.
```

but not great here:

```
$ mlr -n put -v 'func f(n) { return n+1}'
DSL EXPRESSION:
func f(n) { return n+1}

AST:
* statement block
    * function definition "f"
        * parameter list
            * parameter
                * parameter name "n"
        * statement block
            * return "return"
                * operator "+"
                    * local variable "n"
                    * int literal "1"

Variable name n might not have been assigned yet.
```

In the former case a simple pre-order walk of the AST suffices. In the latter case I'd need to take one more step which is to dip into the parameter-list child node, find names of bound parameters, then walk the rest.

Anyway, minor detail and easily overcome. I may not get on this right away but for now it's a proof of concept that this would work. :)

Also on that branch right now (just for experimenting) the check is run unconditionally but for merging to main I'd probably have the uninitialized-variable check only run with a `mlr put -w` flag or somesuch.

Thanks for the nudge!!!!

**Comment by johnkerl** [comment]
@torbiak I completed and merged https://github.com/johnkerl/miller/pull/439/ -- thanks for the nudge! A strict mode will be a bit later on (maybe after Miller 6 general release) but it's a great idea. :D

**Comment by johnkerl** [comment]
https://miller.readthedocs.io/en/latest/reference-dsl.html is updated:

_Since uninitialized out-of-stream variables default to 0 for addition/substraction and 1 for multiplication when they appear on expression right-hand sides (not quite as in awk, where they’d default to 0 either way), the above can be written more succinctly as ..._

**Comment by johnkerl** [comment]
@torbiak I split out https://github.com/johnkerl/miller/issues/440 for the remaining work, and I'll close this issue.

Please let me know if it should be re-opened -- thanks! :D

**Comment by torbiak** [comment]
Awesome, thanks. I tested it out on the most recent situation where I accidentally had an uninitialized local, and it worked as expected except that the warnings go to stdout. I saw in todo.txt that you're considering stderr: why did stdout win for now?

**Comment by johnkerl** [comment]
Ease of regression test tbh ... I need to trap stderrs and stdouts both in my reg-tests and I am not yet. :^/

**Comment by johnkerl** [comment]
(Miller 6 is still feature-incomplete -- several verbs/functions still to be ported ...)

**Comment by johnkerl** [comment]
@torbiak https://github.com/johnkerl/miller/pull/441
