### ISSUE TITLE
Bug with uniq + sort

### ISSUE THREAD

**Issue by trantor** [johnkerl/miller#443]
Hello @johnkerl and as always thanks for the great software.

A colleague of mine has come across what appears to be a bug (or at very least an unforeseen behaviour).

Below a few steps to reproduce
```
$ cat /tmp/example.csv
first,second
1,2
1,2
5,6
3,4
3,4
$ mlr --icsv uniq -a -c /tmp/example.csv
count=2,first=1,second=2
count=1,first=5,second=6
count=2,first=3,second=4
# BUG?
$ mlr --icsv uniq -a -c then sort -n count /tmp/example.csv
# THIS WORKS FINE
$ mlr --icsv uniq -g first,second -c then sort -n count /tmp/example.csv
first=5,second=6,count=1
first=1,second=2,count=2
first=3,second=4,count=2
$ mlr --icsv uniq -a -c /tmp/example.csv
count=2,first=1,second=2
count=1,first=5,second=6
count=2,first=3,second=4
```
The empty output of the first command seems like an anomaly to me.

**Comment by johnkerl** [comment]
Sorry, my pushing a commit auto-closed this issue. :(

Please let me know if I should cut a bugfix release or if HEAD will work for you.

**Comment by trantor** [comment]
Hello @johnkerl . Are you referring to a build to check if the bug is fixed? If not I think I can build it for my use if it's a problem to release a new version now.

**Comment by johnkerl** [comment]
Hi @trantor ! The bug is definitely fixed; question is if you're OK pulling from head & re-compiling & if that will get you up & running.

Context is some users of Millers are more developer-ish & are OK with pulling from head & re-compiling. Others wait for the pre-built platform-specific binaries which are delivered as part of a version release.

Releasing a new version isn't a problem, just a question of urgency for you -- how soon should I do a version release is the question. :)

**Comment by trantor** [comment]
Thanks for the explanation @johnkerl . Personally I'd have no problem with re-compiling it myself, but I know a few colleagues of mine which might prefer a ready-made binary to download.
If it's not too much of a bother could you go with a release? Thanks.

**Comment by johnkerl** [comment]
Sorry delay, RL / work-oncall this week. ETA this weekend. :)

**Comment by trantor** [comment]
:D
No problem

**Comment by johnkerl** [comment]
@trantor https://github.com/johnkerl/miller/releases/tag/v5.10.1

Windows build TBD, & I'll update https://github.com/johnkerl/miller/releases/tag/v5.10.1 with status.
