### ISSUE TITLE
Remove make from build instruction

### ISSUE THREAD

**Issue by 89z** [johnkerl/miller#790]
I see here [1] it says:

~~~
make
~~~

and here [2] it says:

~~~
make
~~~

but Make is not needed, you can just do:

~~~
cd cmd/mlr
go build
~~~

also, not all systems come with Make pre-installed, such as Windows.

1. https://github.com/johnkerl/miller#building-from-source
2. https://miller.readthedocs.io/en/latest/build/#from-git-clone

**Comment by johnkerl** [comment]
@89z good point!

`make` is awesome (and familiar) for people who have it.

We should be equally accomodating for people who don't. _Especially_ since the Go build system is so nice, that people can utter a simple and easy-to-rememer build statement without `make` (which wasn't the case before the Go port).

**Comment by johnkerl** [comment]
@89z with https://github.com/johnkerl/miller/pull/792 -- what do you think?

`make install` doesn't have a good equivalent. I'm not much of a Windows user and would mumble something about "augment your `PATH`" ...

**Comment by 89z** [comment]
What about `go install`? I am on Windows and I use that. You could do something like this:

> Use `go build` to install to current directory, use `go install` to install to GOPATH (`C:\Users\Something\go\bin`)

**Comment by johnkerl** [comment]
Nice, thanks @89z !! :)
