### ISSUE TITLE
Question about 5.10.x branch

### ISSUE THREAD

**Issue by Andy1978** [johnkerl/miller#802]
Sorry for the naive question but is the branch for 5.10.x alive? For example fix #714 was only applied to main.

Is the current 6.0.0 a major step to refractor the codebase or move more legacy C code to Go?

I ask because I ran cppcheck on the 5.10.3 branch and found some resource leaks and also built it with ASAN to find address corruption and I wonder if it's worth to report them or if the 5.10.x codebase is factual "dead"

**Comment by johnkerl** [comment]
Not a naive question at all @Andy1978 ! :) I'm happy to hear interest in leak-checking / address-checking -- this is awesome!

[Miller 6](https://miller.readthedocs.io/en/latest/new-in-miller-6) is the way forward and will soon be released; 5.10.x is terminal.

Miller versioning is all done by tagging HEAD, and branches are all short-lived with merge-to-HEAD on PRs -- with one exception. The only reason I created a [5.10.3 branch](https://github.com/johnkerl/miller/releases/tag/v5.10.3) at all was due to an [ask for a Conda build](https://github.com/johnkerl/miller/issues/740) for Miller 5.10 while Miller 6 is in prep. The Conda build issue required a source mod to resolve (Conda was using `#define NDEBUG` while the Miller code had an old, unrelated `#ifdef NDEBUG` clashing with that), while I had in fact already removed all the C code from `HEAD`. So that branch was for that issue only.

The current 6.0.0 is indeed a [major effort to rewrite/refactor the codebase](https://github.com/johnkerl/miller/blob/main/README-go-port.md); the C code is gone as of the Red PR https://github.com/johnkerl/miller/pull/731, and all functionality is now in Go.

There were multiple reasons I was attached to C (and it has its merits) but on the whole a more modern language such as Go is the better way to proceed. Then leak-checking/valgrind/ASAN will be a thing of the past.

Separate reply to follow about #714

**Comment by johnkerl** [comment]
As for #714 ... I ~am~ was a little confused but I understand now:

* https://github.com/johnkerl/miller/issues/714 was reported October 28
* https://github.com/johnkerl/miller/commit/16f29ed26a03d2a740cab135cf628ab2c78b449c to fix this was committed directly to main Nov 1
* https://github.com/johnkerl/miller/pull/731 was the "Red PR" which removed all C code Nov 4
* https://github.com/johnkerl/miller/issues/740 was the Conda-build issue opened Nov 9
* https://github.com/johnkerl/miller/pull/753 was the 5.10.3 branch opened Nov 16
* https://github.com/johnkerl/miller/releases/tag/v5.10.3 was released as a tag on that branch Nov 16

So 5.10.3 _should_ have gotten the #714 fix ... just now I realized after some head-scratching that my error was in branching 5.10.3 off of 5.10.2 on Nov 16, rather than branching 5.10.3 off of Nov 16's main. Either that or I should have either named it `5.10.2.conda`.

Sorry for the confusion!

If this is urgent we can make a 5.10.4 to include #714. Otherwise Miller 6.0.0 will be released as soon as I can -- I'm hoping to make a final drive over the winter break.

**Comment by johnkerl** [comment]
P.S. Good catch with lemon-parser file-closes on https://github.com/Andy1978/miller/commit/661643f8cf0bfaf325c56c1013cc2d88bfbfb853

Your work there got me thinking ... `cppcheck` is of course a non-issue in Go ... there are, however, more things that can be done now that Miller is in Go:

* Memory is GC'ed so memory-leak checking of course goes away; however for perf-tuning I've made some use of [flame graphs etc](https://github.com/johnkerl/miller/blob/main/cmd/mlr/main.go#L36-L64) and have found this very insightful.
* File-close leaks are still possible in Go and could be hunted for. I'd also add that a Miller design issue in C as well as Go is that if people do `tee $foo` for some high-cardinality field name `$foo` then one can run out of open descriptors -- not a "leak" per se (all opened tee-files will get closed) but rather if there are more distinct values of `$foo` in the file than descriptors available, the process will crash -- which could addressed with some close-and-reopen logic.
* Go-linting with `golangci-lint` is another ball of wax -- we use it at work a bit & I find it a bit of a signal-to-noise issue. After the 6.0.0 release, I think it'd be interesting to maybe refine down to a more-noise-than-signal lint-config, and use that to look for potential issues in Miller.
* There's also https://staticcheck.io which I haven't looked into at all
* Do you know about this or other static analysis and/or leak-analysis tools for Go?

**Comment by jauderho** [comment]
@johnkerl There is https://github.com/praetorian-inc/gokart if you have not looked into it before.

Other tooling that might be a consideration for implementing (I can submit pull requests):

* pyroscope (useful for profiling while running)
* super-linter (this can lint per commit but will require tuning)
* https://goreportcard.com/report/github.com/johnkerl/miller
* codespell
* CodeQL
* Semgrep

Also, with 1.18beta/gotip, you can set up fuzzing although I have not tried this myself yet.

**Comment by jauderho** [comment]
I was curious and quickly ran gokart on the miller codebase. 

Here's the output: https://gist.github.com/jauderho/5009998729607e140dacf8787b04d14e

**Comment by johnkerl** [comment]
@jauderho awesome, thanks!!

https://github.com/johnkerl/miller/issues/812
https://github.com/johnkerl/miller/issues/813

**Comment by johnkerl** [comment]
@Andy1978 closing in light of tracking issues split out from this -- please let me know if I'm mistaken & we need to reopen -- thank you!
