### ISSUE TITLE
Dealing with empty fields

### ISSUE THREAD

**Issue by lindig** [johnkerl/miller#83]
$ echo 'foo,bar,baz' | mlr cat
    1=foo,2=bar,3=baz
    $ echo 'foo,bar,' | mlr cat
    Empty key disallowed.

I'm not sure whether this is a matter of documentation or implementation: I'd like to process input that includes empty fields but I get the idea that this is not possible. However, I don't understand why this would pose a problem for the tool. If this is a general limitation, it needs to be better documented as it is fairly limiting.

I was using the most recent version of Miller from Homebrew "This is Miller version >= 2.2.1.".

**Comment by johnkerl** [comment]
Thanks. You are right.

The intention was to disallow empty *keys* for the same reason I disallow empty fields in CSV headers. A CSV data line can have an empty field; a CSV header line cannot. I imitated that reasoning for DKVP format. Yet, at some point I realized that for DKVP fields without pair separator (default `=`) I could numerically index them. Examples:

```
$ echo 'x=a,y=b,z=c' | mlr --idkvp --oxtab cat
x a
y b
z c

$ echo 'x=a,y=,z=c' | mlr --idkvp --oxtab cat
x a
y 
z c

$ echo 'a,b,c' | mlr --idkvp --oxtab cat
1 a
2 b
3 c
```
This already works OK for NIDX format:
```
$ echo 'a,,c' | mlr --inidx --ifs , --oxtab cat
1 a
2 
3 c

$ echo 'a,,c' | mlr --idkvp --oxtab cat
mlr: empty key at file "(stdin)" record 0.
```

This will be fixed in my next commit:
```
$ echo 'a,,c' | mlr --idkvp --oxtab cat
1 a
2 
3 c
```

As a side note, I have a note to myself to update the brew recipe to current Miller package version. Hence your error-message wording different than mine.

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/commit/6bc93bb332ab27985c309d162f560075d35f6dc7

**Comment by johnkerl** [comment]
To get this fix, you can git pull and build from source; or, I'll be cutting a new release very soon & I'll put up an OSX executable as always.

**Comment by johnkerl** [comment]
I'm going to go ahead & close this -- please let me know if that's in error.

Thank you!! :)

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/issues/84 for the brew-update issue.
