### ISSUE TITLE
[mlr 6] Interaction of ANSI color sequences and quoting, for some values of OFS

### ISSUE THREAD

**Issue by schragge** [johnkerl/miller#853]
Not sure if this has to be considered a bug. If the `--ofs` delimiter appears inside the ANSI color sequences, the colored output to terminal will quote all the fields.
```
echo a,b,c|mlr -cN --ofs \; cat
```
Redirecting output or specifying `-M` will remove the excessive quoting
```
echo a,b,c|mlr -cNM --ofs \; cat
```
In principle, I could abuse this to emulate the old `--quote-all` behavior
```
mlr -CcN --ofs \; cat|ansi2txt|
  csvquote -d\;|tr \; ,|csvquote -ud\;
```
Although I wouldn't do this in practice as there are [many other ways](https://www.linuxquestions.org/questions/linux-newbie-8/insert-double-quotes-for-fields-in-csv-4175673089) to achieve the same.

**Comment by johnkerl** [comment]
@schragge confirmed repro, and definitely a bug. The `--ofs` and the colorization should be completely orthogonal to one another and are evidently not when `OFS` is `;` :^/

**Comment by schragge** [comment]
> when `OFS` is `;` :^/

Or `[`  which, admittedly, is contrived.

**Comment by johnkerl** [comment]
indeed ... some cleniration with the ANSI escape-sequence characters then ... 😕

**Comment by johnkerl** [comment]
Oh @schragge this is one of those obvious-in-retrospect kinds of things ...

https://github.com/johnkerl/miller/blob/main/internal/pkg/output/record_writer_csv.go#L87-L93

The Go `encoding/csv` package's `Writer` class' `write` method is responsible for joining on `Comma` (Miller `OFS`, with an added limitation that it needs to be single-character) -- and first wrapping each field if the field has `Comma` or newline anywhere in it. Which ... they do, since they have the ANSI escape sequences contained within the field values:
https://github.com/johnkerl/miller/blob/39bb43381a4318795f894fc68f845a20a40eae32/internal/pkg/colorizer/colorizer.go#L246

So ... I don't see much to do here except to document it as a quirk ... :^/ ... or maybe if the output is a terminal, then bypass `csv.Writer.Write` and roll my own. I prefer to use well-optimized system libraries for performance, of course, but, for the case when output is already to the terminal and already being colorized, I suppose performance is a non-concern so rolling my own should be OK ...

**Comment by schragge** [comment]
>  Which ... they do, since they have the ANSI escape sequences contained within the field values:

Yes, this is what I meant from the start by saying "If the `--ofs` delimiter appears inside the ANSI color sequences". Sorry, I'm not a native English speaker. Perhaps, I should have formulated this differently: "If the `--ofs` delimiter appears as part of the ANSI color sequences".

**Comment by johnkerl** [comment]
> Sorry, I'm not a native English speaker

Oh wow, I had no idea! I wish I had a second language as strong as you have English :)

OK, great -- I think the roll-my-own substitue for `csv.Writer.write` should be straightfoward & this should work out pretty quickly

Thanks for letting me know about this! :)
