### ISSUE TITLE
mktemp possibly used unsafely

### ISSUE THREAD

**Issue by jungle-boogie** [johnkerl/miller#86]
While researching issue #85, came across this during a build:

`/tmp/mlr_test_util-19aa81.o: In function `write_temp_file_or_die':
lib/mlr_test_util.c:(.text+0x24): warning: warning: mktemp() possibly used unsafely; consider using mkstemp()
/tmp/mlr_test_util-435aca.o: In function `write_temp_file_or_die':
/home/vagrant/bin/miller/c/lib/mlr_test_util.c:10: warning: warning: mktemp() possibly used unsafely; consider using mkstemp()
/tmp/mlr_test_util-cfe51b.o: In function `write_temp_file_or_die':
/home/vagrant/bin/miller/c/lib/mlr_test_util.c:10: warning: warning: mktemp() possibly used unsafely; consider using mkstemp()`

**Comment by johnkerl** [comment]
Thanks.

**Comment by johnkerl** [comment]
The last two are due to missing single quotes on your shell commands.

I'm sure there's a system-dependent regression here but I'm skeptical that your bisection has identified the culprit commit. In a couple days I'll get you some experiments to run if you don't mind.

Also I need to set up a FreeBSD VM or something to shorten these cross-platform debug cycles.

**Comment by johnkerl** [comment]
Oops commented on wrong issue.
