### ISSUE TITLE
[mlr 6] Wrong operator precedence for concatenation operator (`.`)

### ISSUE THREAD

**Issue by schragge** [johnkerl/miller#909]
This is different from #906.

Just found out that the old code [here](https://www.linuxquestions.org/questions/linux-newbie-8/make-a-sum-in-the-awk-command-4175674013/#post6117398) doesn't work in Miller 6 anymore. The code in question
```
seq 50 |
 mlr --nidx put -q '
   @sum+=$1;@num[NR]=$1;
   end{
     for (k,v in @num){print v."\t".v/@sum}
   }'
```
which of course can be rewritten as `seq 50|mlr --n2t -N fraction -f 1`

Putting parentheses around `v/@sum` makes the old code work again.

The documentation [says](https://github.com/johnkerl/miller/blob/01ed355bcafded5b19c0057aaa3594df16cfc72f/docs/src/reference-dsl-operators.md.in#L16)
```
| binary`*` `/` `//` `%`        | left to right |
| `.`                           | left to right |
```

**Comment by johnkerl** [comment]
Thanks @schragge !!

For context, this was due to https://miller.readthedocs.io/en/latest/reference-dsl-operators/#the-double-purpose-dot-operator -- formerly `.`, when only for concatenation, was on par with `+` and `-` -- some languages use `+` for string-concatenation; Miller uses `.`.  But in Miller 6 I wanted some support for simpler traversal of JSON data.

https://github.com/johnkerl/miller/blob/main/internal/pkg/parsing/mlr.bnf#L1462

```
$ mlr5 -n put -v 'a = b / c . d' | chop
RAW AST:

AST ROOT:
text="block", type=STATEMENT_BLOCK:
    text="=", type=NONINDEXED_LOCAL_ASSIGNMENT:
        text="a", type=NONINDEXED_LOCAL_VARIABLE.
        text=".", type=OPERATOR:
            text="/", type=OPERATOR:
                text="b", type=NONINDEXED_LOCAL_VARIABLE.
                text="c", type=NONINDEXED_LOCAL_VARIABLE.
            text="d", type=NONINDEXED_LOCAL_VARIABLE.
```

```
$ mlr -n put -v 'a = b / c . d'
DSL EXPRESSION:
a = b / c . d

AST:
* statement block
    * assignment "="
        * local variable "a"
        * operator "/"
            * local variable "b"
            * dot operator "."
                * local variable "c"
                * local variable "d"
```
