### ISSUE TITLE
Issue with stats1 max

### ISSUE THREAD

**Issue by standage** [johnkerl/miller#92]
When running the following command on [Amel.pre-mrnas.tsv](https://gist.github.com/standage/f0e6c949e5ba07eddf5f) I get the following output.

```
mlr --csv --fs tab --rs lf stats1 -a mean,p50,min,max -f Length scratch/species/Amel/Amel.pre-mrnas.tsv 
Length_mean	Length_p50	Length_min	Length_max
13139.399587	3557	105	105
```

It looks like max is simply reporting the min value. This happens for lots of different files.
If I replace `max` with `p100`, however, I get the correct result.

```
$ mlr --csv --fs tab --rs lf stats1 -a mean,p50,min,p100 -f Length scratch/species/Amel/Amel.pre-mrnas.tsv 
Length_mean	Length_p50	Length_min	Length_p100
13139.399587	3557	105	904366
```

I'm running the current master.

**Comment by johnkerl** [comment]
Thank you.

This was introduced in https://github.com/johnkerl/miller/commit/4575f1fe5831cab51aaf19cffc605f1b4a2372ab. It's fixed by https://github.com/johnkerl/miller/commit/d1cd066844f1b2ab14fdb4225b70428c803ee62b.

I am very much unhappy with myself for this ... regression tests are designed to catch precisely such errors. As it was, I made a diff with rather sweeping changes and missed the break among the details of the diff.

I'll cut a 3.1.2 bugfix release.

**Comment by johnkerl** [comment]
https://github.com/johnkerl/miller/releases/tag/v3.1.2

**Comment by standage** [comment]
https://github.com/Homebrew/homebrew/pull/46835
