### ISSUE TITLE
Quoting and TSV input

### ISSUE THREAD

**Issue by aborruso** [johnkerl/miller#922]
Hi,
when I run

```
mlr --tsv cat https://gist.githubusercontent.com/aborruso/055fdd088f4f4e91b80b445a4b906210/raw/cd297b662a75b45af457be6fd5f0ce9de69a1b30/tmp.txt
```

I have 

```
mlr :  mlr: CSV header/data length mismatch 27 != 23 at filename https://gist.githubusercontent.com/aborruso/055fdd088f4f4e91b80b445a4b906210/raw/cd297b662a75b45af457be6fd5f0ce9de69a1b30/tmp.txt row 7.
```

The problem is in `"`. Ok, I know how to solve it, but my question is: does this input file anything that is wrong?

Probably this issue could be related to #438

**Comment by johnkerl** [comment]
Hi @aborruso !

* This is indeed related to #438.
* But also even without that, using

```
mlr --inidx --ifs tab --oxtab cat https://gist.githubusercontent.com/aborruso/055fdd088f4f4e91b80b445a4b906210/raw/cd297b662a75b45af457be6fd5f0ce9de69a1b30/tmp.txt
```

I can see that the last line has 26 fields while all the lines before have 27.

What can be done about this:

* Fixing #438 is long overdue. While in Miller 5 below I had a homegrown CSV parser, for Miller 6 I'm using Go's [pkg.go.dev/encoding/csv](https://pkg.go.dev/encoding/csv). This in turn has an option called `LazyQuotes` which I can use to fix #438. Namely:
  * Make a Miller command-line flag `--csv-lazy-quotes` which will be passed along to use `LazyQuotes` in the CSV reader
  * Have lazy-quotes set to true automatically whenever input is TSV
* Using that combined with `--allow-ragged-csv-input` we'll be able to parse the above file.

**Comment by aborruso** [comment]
@johnkerl I'm sorry I have shared a wrong input file. I wanted to share a small version, but I made some mistakes in creating it

Mi input file is this https://zenodo.org/record/5112881

If I try to `mlr --tsv cat` I have

```
mlr :  mlr: CSV header/data length mismatch 27 != 23 at filename input.tsv row 7.
```

And I have solved via `csvlite`, `mlr --csvlite --ifs tab`.
If I remove from the input all the `"` I have no error.

This TSV is not a ragged input. Am I wrong? If it has no errors, I think it may be useful to note this case for the future.

As usual thank you

**Comment by johnkerl** [comment]
@aborruso the file is fine.

Something I should have done _much_ sooner is to take a careful look at https://en.wikipedia.org/wiki/Tab-separated_values. Namely, embedded tab and newline are _simply disallowed_ in the TSV spec.

So Miller has had (ever since Miller 2.0) **CSV** which is RFC-4180-compliant, handling embedded commas and newlines, and doing double-double-quoting, etc and **CSV-lite** which doesn't allow embedded commas and newlines, need no (and offers no) treatment of double quotes differently than any other character.

So far so good.

All along I've had TSV and TSV-lite, being the same as CSV and CSV-lite but with tab instead of comma. But this isn't OK. The spec for CSV (RFC 4180) requires special handling for commas, newlines, and double quotes. The spec for TSV requires no such.

This means that what I've always called TSV-lite is really spec-compliant TSV. And what I've always called TSV is not compliant with anything -- it does things with double quotes that it shouldn't; hence #438 for example.

In the immediate term what you can do for the above dataset is simply use `--tsvlite`.

```
$ mlr --itsv check mesibov.tsv
mlr :  mlr: CSV header/data length mismatch 27 != 8 at filename mesibov.tsv row 3116.

$ echo $?
1

$ mlr --itsvlite check mesibov.tsv

$ echo $?
0
```

What I should do -- probably for the next release -- is make sure `--tsv` is handled internally the same as `--tsvlite` since that will (at long last) make Miller's TSV handling compliant with the IANA TSV specification.

**Comment by johnkerl** [comment]
@aborruso https://github.com/johnkerl/miller/pull/923 https://miller.readthedocs.io/en/latest/file-formats/#csvtsvasvusvetc

**Comment by johnkerl** [comment]
@aborruso see also https://github.com/johnkerl/miller/pull/925 which may sometimes be useful

**Comment by johnkerl** [comment]
@aborruso closing this -- please let me know if I missed anything & we can re-open -- thank you!

**Comment by aborruso** [comment]
> @aborruso closing this -- please let me know if I missed anything & we can re-open -- thank you!

It works, and it's great, because now it's a real TSV and TSV is a very important format in data science.

I'm very proud of this issue 🖖
